In [6]:
import pyodbc
import pandas as pd

In [10]:
def get_data(query: str):

    # define DPlus database connection string
    CONNECTION_STRING = f"""
        DSN=DPlus;
        HOST=18.230.98.143;
        DB=distrib;
        UID=readonly;
        PWD=readonlypass;
        PORT=2609;
    """

    # instantiate connection and cursor objects
    connection = pyodbc.connect(CONNECTION_STRING)
    cursor = connection.cursor()

    # retrieve data and dump it in a dataframe
    records = cursor.execute(query).fetchall()
    columns = [column[0] for column in cursor.description]    
    df = pd.DataFrame.from_records(
        data=records,
        columns=columns
    )

    # close connection
    cursor.close()
    connection.close()
    
    return df

In [11]:
query = f"""
        SELECT l.codart,
            a.descrip,
            l.precio AS 'precio_unitario',
            l.cant AS 'bultos',
            l.resto AS 'unidades',
            a.resto AS 'undsxblt',
            l.bonif / 100 AS 'bonificacion',
            l.internos,
            l.iva1
        FROM PUB.lineas l
        LEFT JOIN PUB.tipodocs td ON l.iddocumento = td.iddocumento
        LEFT JOIN PUB.articulos a ON l.codart = a.codart
        WHERE l.anulado = 0 AND
            l.iddocumento = 'FCVTA' AND
            l.letra = 'A' AND
            l.serie = 2 AND
            l.nrodoc = 32877
    """

In [13]:
df = get_data(query)
df

,codart,descrip,precio_unitario,bultos,unidades,undsxblt,bonificacion,internos,iva1
0,2218,QUILMES - 4X6 LAT 473,5700.968,5,0,24,0.46020000,2046.41000,3231.25110
1,21862,CORONA CAN 4X6 410CC 6P CART,9803.240,2,0,24,0.50080000,1969.42000,2055.38550
2,7026,QUILMES - X12 1000RET,5104.352,5,0,12,0.46020000,1780.69000,2893.09650
3,19253,ANDES ORIGEN IPA RET X12 1000,5716.452,1,0,12,0.39100000,450.34000,731.07720
4,19341,7-UP RECO X8 2000 NF,2956.517,1,0,8,0.41100000,168.29000,365.69190
5,24880,STELLA ARTOIS PM RET X12 975CC,7246.611,1,0,12,0.39100000,571.70000,926.76990
6,1473,PASO DLT POMELO * X8 PET2250#,4845.124,1,0,8,0.44200000,370.34000,567.75180
7,16667,ANDES ORIGEN ROJA RET X12 1000,5716.452,1,0,12,0.39100000,450.34000,731.07720
8,14191,PEPSI BLACK PET X6 1500,3211.692,3,0,6,0.62800000,491.69000,752.69250
9,21810,BUDWEISER CAN 4X6 410CC 6PACK,5904.235,2,0,24,0.46020000,1281.65000,1338.58410

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   codart           10 non-null     int64
 1   descrip          10 non-null     object
 2   precio_unitario  10 non-null     object
 3   bultos           10 non-null     int64
 4   unidades         10 non-null     int64
 5   undsxblt         10 non-null     int64
 6   bonificacion     10 non-null     object
 7   internos         10 non-null     object
 8   iva1             10 non-null     object
dtypes: int64(4), object(5)
memory usage: 848.0+ bytes